name: CI
on:
  push:
    branches:
      - master
      - dev
      - 'release-*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  KERNEL_VENV: .local-venv

jobs:
  test:
    name: Test (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install prerequisites
      run: |
        python -m pip install -r test/requirements-site.txt
    - name: Build PyPI distributions
      run: make build
    - name: Check dist files
      run: twine check dist/*
    - name: Install wheel
      run: |
        python -m pip install dist/*.whl
    - name: Set up project environment for test
      run: |
        python -m venv .local-venv
        .local-venv/bin/python -m pip install -r test/requirements-local.txt
    - name: Run test
      run: |
        python test/test_kernel.py
  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install prerequisites
      run: |
        python -m pip install -r test\requirements-site.txt
    - name: Install package
      run: |
        python -m pip install .
    - name: Set up project environment for test
      run: |
        python -m venv .local-venv
        .\.local-venv\Scripts\activate
        python -m pip install -r test\requirements-local.txt
    - name: Run test
      run: |
        python test\test_kernel.py
  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff --line-length 79"
          version: "~= 23.0"
