name: Publish
on:
  push:
    tags:
    - '*'

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m pip install build wheel --user
    - name: Build PyPI distributions
      run: |
        python -m build --no-isolation
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_PYTHON_LOCALVENV_KERNEL }}
